CREATE TABLE user (
    id INT AUTO_INCREMENT PRIMARY KEY,  
    email VARCHAR(50) UNIQUE NOT NULL,
    age INT(2) NOT NULL,
    password VARCHAR(255) NOT NULL,
    create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)